name: release-please test
on:
  push:
    branches:
      - main
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: release-please-action
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
  hoge:
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - name: In steps release_created
        if: ${{ needs.release-please.outputs.release_created }}
        run: |
          echo "in steps release created"
      - name: In steps not release_created
        if: ${{ needs.release-please.outputs.release_created == false }}
        run: |
          echo "in steps release not created"
  release-created:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - run: |
          echo "in job release_created"
  release-not-created:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == false }}
    steps:
      - run: |
          echo "in job not release_created"

